version: '3.3'

networks:
  portal:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  mysql:
    image: mysql/mysql-server:8.0.23
    networks:
      portal:
        ipv4_address: 172.21.0.6
    ports:
      - '3306:3306'
    #  volumes:
    #    - /data/proto/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
